"""
Data models for CabinPython v2 daemon.

This module defines the core data structures used throughout the system.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, Any, Optional


class SensorType(Enum):
    """Type of sensor connection pattern."""

    POLLING = "polling"          # Polled at intervals (SHT31, ModBus)
    CONTINUOUS = "continuous"    # Maintains connection (future sensors)
    API = "api"                  # External API calls (WeatherFlow)


@dataclass
class SensorReading:
    """
    Standard sensor reading format.

    All sensors must return data in this format to ensure consistent
    processing through the plugin system.

    Attributes:
        sensor_id: Unique identifier for the sensor
        timestamp: When the reading was taken
        measurements: Dictionary of measurement name -> value
        metadata: Optional additional context (e.g., units, quality indicators)
        error: Optional error message if reading failed
    """

    sensor_id: str
    timestamp: datetime
    measurements: Dict[str, Any]
    metadata: Optional[Dict[str, Any]] = None
    error: Optional[str] = None

    @property
    def is_valid(self) -> bool:
        """Check if reading is valid (no error and has measurements)."""
        return self.error is None and bool(self.measurements)

    def __repr__(self) -> str:
        """Readable representation of sensor reading."""
        if self.error:
            return f"SensorReading(sensor_id={self.sensor_id}, error={self.error})"
        return f"SensorReading(sensor_id={self.sensor_id}, measurements={len(self.measurements)} fields)"


@dataclass
class Event:
    """
    Event or alarm generated by the system.

    Events are generated when:
    - Sensor values cross thresholds
    - Sensor states change
    - System errors occur
    - Circuit breakers trip

    Attributes:
        event_type: Type of event (e.g., 'battery_low', 'sensor_failure')
        severity: Event severity level
        sensor_id: Sensor that triggered the event (if applicable)
        message: Human-readable event description
        data: Additional event data
        notify: Whether to send notifications for this event
    """

    event_type: str
    severity: str  # 'info', 'warning', 'error', 'critical'
    timestamp: datetime = field(default_factory=datetime.now)
    sensor_id: Optional[str] = None
    message: str = ""
    data: Dict[str, Any] = field(default_factory=dict)
    notify: bool = False

    def __repr__(self) -> str:
        """Readable representation of event."""
        return f"Event({self.severity.upper()}: {self.event_type} - {self.message})"


@dataclass
class HealthStatus:
    """
    Health status for a component (sensor, output, or daemon).

    Used by health monitoring to track component states.

    Attributes:
        component_id: Unique identifier for the component
        status: 'healthy', 'degraded', or 'failed'
        last_success: Timestamp of last successful operation
        last_failure: Timestamp of last failure
        failure_count: Number of consecutive failures
        message: Status message
    """

    component_id: str
    status: str  # 'healthy', 'degraded', 'failed'
    last_success: Optional[datetime] = None
    last_failure: Optional[datetime] = None
    failure_count: int = 0
    message: str = ""

    @property
    def is_healthy(self) -> bool:
        """Check if component is healthy."""
        return self.status == "healthy"

    def __repr__(self) -> str:
        """Readable representation of health status."""
        return f"HealthStatus({self.component_id}: {self.status.upper()})"
